### ISSUE TITLE
Game crash after mission failed or load game

### ISSUE THREAD

**Issue by soucevit** [iortcw/iortcw#184]
Hi,
I did not found this issue anywhere so I hope it is just not something stupid on my side in config.

I am running linux version 1.15c on latest lubuntu. Game runs fine with laptops native resolution and maxxed quality. so there is no performance issue. However almost every time mission fails, game crashes during the fade out. It also crashes sometimes when loading game while in the mission. Start the game or load in freshly started application works fine. I tried running it with safe settings. it happens in full screen or window. I disabled both extra features for nVidia and ATI as i have just onboard Intel GPU. 

I ran the game in console and this is the output, hope it helps:

```
iortcw 1.51c-SP linux-x86_64 Mar 16 2019
SSE instruction set enabled
----- FS_Startup -----
Current search path:
/home/soucevit/.wolf/main
/home/soucevit/Games/iortcw-1.51c-linux-x86_64/main/sp_rend2_shaders0.pk3 (5 files)
/home/soucevit/Games/iortcw-1.51c-linux-x86_64/main/sp_pak4.pk3 (21 files)
/home/soucevit/Games/iortcw-1.51c-linux-x86_64/main/sp_pak3.pk3 (14 files)
/home/soucevit/Games/iortcw-1.51c-linux-x86_64/main/sp_pak2.pk3 (232 files)
/home/soucevit/Games/iortcw-1.51c-linux-x86_64/main/sp_pak1.pk3 (1342 files)
/home/soucevit/Games/iortcw-1.51c-linux-x86_64/main/pak0.pk3 (4775 files)
/home/soucevit/Games/iortcw-1.51c-linux-x86_64/main
    
----------------------
6389 files in pk3 files
execing default.cfg
execing wolfconfig.cfg
couldn't exec autoexec.cfg
Hunk_Clear: reset the hunk ok
Bypassing CD checks
----- Client Initialization -----
Couldn't read rtcwhistory.
Cmd_AddCommand: map_restart already defined
----- Initializing Renderer ----
Trying to load "renderer_sp_rend2_x86_64.so" from "/home/soucevit/Games/iortcw-1.51c-linux-x86_64"...
---- Renderer Initialization Complete ----
RTCWKEY found.
----- Client Initialization Complete -----
----- R_Init -----
SDL using driver "x11"
Initializing OpenGL display
Display aspect: 1.778
...setting mode 26: 1920 1080
Trying to get an OpenGL 3.2 core context
SDL_GL_CreateContext succeeded.
Using 24 color bits, 24 depth, 8 stencil display.
Available modes: '320x180 432x243 480x270 512x288 640x360 720x405 800x450 864x486 960x540 1024x576 1280x720 1440x810 1600x900 1920x1080 360x202 684x384 1368x768 840x525 960x600 1280x800 1680x1050 700x450 1400x900 320x240 400x300 512x384 640x480 700x525 800x600 896x672 928x696 960x720 1024x768 1280x960 1400x1050 640x512 1280x1024'
GL_RENDERER: Mesa Intel(R) HD Graphics 620 (KBL GT2)
Initializing OpenGL extensions
...GL_EXT_texture_compression_s3tc not found                                                                                                                                                 
...ignoring GL_S3_s3tc                                                                                                                                                                       
...ignoring GL_EXT_texture_filter_anisotropic                                                                                                                                                
...using GL_ARB_framebuffer_object                                                                                                                                                           
...using GL_ARB_vertex_array_object                                                                                                                                                          
...using GL_ARB_texture_float                                                                                                                                                                
...using GL_ARB_depth_clamp                                                                                                                                                                  
...ignoring GL_ARB_seamless_cube_map
...using GLSL version 4.60
...GL_NVX_gpu_memory_info not found
...GL_ATI_meminfo not found
...ignoring GL_ARB_texture_compression_rgtc
...ignoring GL_ARB_texture_compression_bptc
...GL_EXT_direct_state_access not found
------- FBO_Init -------
------- GLSL_InitGPUShaders -------
loaded 276 GLSL shaders (192 gen 42 light 42 etc) in  0.14 seconds
------- R_InitVaos -------
Initializing Shaders
^3WARNING: In shader file scripts/common.shader...Shader "textures/sfx/portal3a_back2" on line 822 is missing closing brace^3.
^3WARNING: In shader file scripts/ui_wolf.shader...Invalid shader name "}" on line 1849.
----- finished R_Init -----
------ Initializing Sound ------
Trying to load "libopenal.so.1"...
Allocated 128 sources.
OpenAL default capture device is 'Vnitřní zvukový systém Analogové stereo'
OpenAL capture device opened.
OpenAL info:
  Vendor:         OpenAL Community
  Version:        1.1 ALSOFT 1.19.1
  Renderer:       OpenAL Soft
  AL Extensions:  AL_EXT_ALAW AL_EXT_BFORMAT AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_BFORMAT AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_EXT_SOURCE_RADIUS AL_EXT_STEREO_ANGLES AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFTX_events AL_SOFTX_filter_gain_ex AL_SOFT_gain_clamp_ex AL_SOFT_loop_points AL_SOFTX_map_buffer AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length AL_SOFT_source_resampler AL_SOFT_source_spatialize
  ALC Extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFT_device_clock ALC_SOFT_HRTF ALC_SOFT_loopback ALC_SOFT_output_limiter ALC_SOFT_pause_device
  Device:         Vnitřní zvukový systém Analogové stereo
  Available Devices:
Vnitřní zvukový systém Analogové stereo
  Input Device:   Vnitřní zvukový systém Analogové stereo
  Available Input Devices:
Vnitřní zvukový systém Analogové stereo
Monitor of Vnitřní zvukový systém Analogové stereo
Sound initialization successful.
--------------------------------
--- Common Initialization Complete ---
IP: 127.0.0.1
IP: 192.168.1.55
IP6: ::1
IP6: fdf1:2eba:b2a:a145:1a0b:e63c:bae1:18c7
IP6: fdf1:2eba:b2a:a145:e1aa:d772:783f:47a4
IP6: fe80::19b7:ef0e:98ba:8693%wlp2s0
Opening IP6 socket: [::]:27960
Opening IP socket: 0.0.0.0:27960
sv_maxclients will be changed upon restarting.
------ Server Initialization ------
Server: church
RE_Shutdown( 0 )
------- FBO_Shutdown -------
------- R_ShutdownVaos -------
------- GLSL_ShutdownGPUShaders -------
Hunk_Clear: reset the hunk ok
----- FS_Startup -----
Current search path:
/home/soucevit/.wolf/main
/home/soucevit/Games/iortcw-1.51c-linux-x86_64/main/sp_rend2_shaders0.pk3 (5 files)
/home/soucevit/Games/iortcw-1.51c-linux-x86_64/main/sp_pak4.pk3 (21 files)
/home/soucevit/Games/iortcw-1.51c-linux-x86_64/main/sp_pak3.pk3 (14 files)
/home/soucevit/Games/iortcw-1.51c-linux-x86_64/main/sp_pak2.pk3 (232 files)
/home/soucevit/Games/iortcw-1.51c-linux-x86_64/main/sp_pak1.pk3 (1342 files)
/home/soucevit/Games/iortcw-1.51c-linux-x86_64/main/pak0.pk3 (4775 files)
/home/soucevit/Games/iortcw-1.51c-linux-x86_64/main
    
----------------------
6389 files in pk3 files
Gametype changed, clearing session data.
------- BotLib Initialization -------
------------ Map Loading ------------
trying to load maps/church_b0.aas
loaded maps/church_b0.aas
trying to load maps/church_b1.aas
loaded maps/church_b1.aas
-------------------------------------
AAS initialized.
AAS initialized.
-----------------------------------
RE_Shutdown( 0 )
----- R_Init -----
------- FBO_Init -------
------- GLSL_InitGPUShaders -------
loaded 276 GLSL shaders (192 gen 42 light 42 etc) in  0.11 seconds
------- R_InitVaos -------
Initializing Shaders
^3WARNING: In shader file scripts/common.shader...Shader "textures/sfx/portal3a_back2" on line 822 is missing closing brace^3.
^3WARNING: In shader file scripts/ui_wolf.shader...Invalid shader name "}" on line 1849.
----- finished R_Init -----
LOADING... collision map
LOADING... sounds
    
.........................
Initializing Sound Scripts
...loading 'sound/scripts/cutscene1.sounds'
...loading 'sound/scripts/cutscene6.sounds'
...loading 'sound/scripts/cutscene9.sounds'
...loading 'sound/scripts/cutscene11.sounds'
...loading 'sound/scripts/cutscene14.sounds'
...loading 'sound/scripts/cutscene19.sounds'
...loading 'sound/scripts/escape1.sounds'
...loading 'sound/scripts/escape2.sounds'
...loading 'sound/scripts/tram.sounds'
...loading 'sound/scripts/village1.sounds'
...loading 'sound/scripts/crypt1.sounds'
...loading 'sound/scripts/crypt2.sounds'
...loading 'sound/scripts/church.sounds'
...loading 'sound/scripts/boss1.sounds'
...loading 'sound/scripts/forest.sounds'
...loading 'sound/scripts/rocket.sounds'
...loading 'sound/scripts/assault.sounds'
...loading 'sound/scripts/sfm.sounds'
...loading 'sound/scripts/factory.sounds'
...loading 'sound/scripts/trainyard.sounds'
...loading 'sound/scripts/swf.sounds'
...loading 'sound/scripts/norway.sounds'
...loading 'sound/scripts/xlabs.sounds'
...loading 'sound/scripts/boss2.sounds'
...loading 'sound/scripts/dam.sounds'
...loading 'sound/scripts/village2.sounds'
...loading 'sound/scripts/chateau.sounds'
...loading 'sound/scripts/dark.sounds'
...loading 'sound/scripts/castle.sounds'
...loading 'sound/scripts/end.sounds'
...loading 'sound/scripts/ai.sounds'
...loading 'sound/scripts/general.sounds'
...loading 'sound/scripts/combat.sounds'
...loading 'sound/scripts/movers.sounds'
done.
LOADING... graphics
LOADING... maps/church.bsp
stitched 0 LoD cracks
...loaded 12546 faces, 12 meshes, 22 trisurfs, 12 flares
LOADING... game media
LOADING...  - textures
LOADING...  - models
LOADING...  - weapons
LOADING...  - items
LOADING...  - inline models
LOADING...  - server models
LOADING...  - particles
LOADING...  - game media done
LOADING... flamechunks
LOADING... clients
LOADING... WolfPlayer
UI menu load time = 1 milli seconds
CL_InitCGame:  0.85 seconds
40 msec to draw all images
Com_TouchMemory: 0 msec
----- Client Shutdown (Received signal 11) -----
RE_Shutdown( 1 )
------- FBO_Shutdown -------
------- R_ShutdownVaos -------
------- GLSL_ShutdownGPUShaders -------
OpenAL capture device closed.
-----------------------
----- Server Shutdown (Received signal 11) -----
tty]
```

**Comment by MAN-AT-ARMS** [comment]
I would suggest building from source since 1.51c is a few years old.

**Comment by hbokh** [comment]
This happens too on macOS (version 14.4.1 - arm64) when playing  the x86_64 binary with Rosetta.

I build an arm64 binary from source (master branch / `VERSION: 1.51d-SP_GIT_a4e6f501-2024-03-12`) with `make-macosx.sh arm64`).
It sometimes has the same issue, playing directly from the build dir with`iowolfsp.arm64`.

Tested with ["Wolfenstein: Enemy Territory Single-Player (1.23)"](https://www.moddb.com/mods/et/downloads/etsp-zip) and this command: `~/Games/iowolfsp.app/Contents/MacOS/iowolfsp +set fs_game ET` seems to keep up.

**Comment by dumol** [comment]
Reproducible with Flathub package at https://flathub.org/en-GB/apps/com.github.iortcw.iortcw (also version 1.51c).

If this is fixed after 1.51c release, maybe issue a new one and update Flathub package too?

Thanks!

**Comment by iiv3** [comment]
This patch should workaround the crash, by forcing a slow reload of the map.

```
--- SP/code/server/sv_ccmds.c.org    
+++ SP/code/server/sv_ccmds.c 
@@ -357,7 +357,7 @@
 
        // check for changes in variables that can't just be restarted
        // check for maxclients change
-       if ( sv_maxclients->modified || sv_gametype->modified ) {
+       if ( 1 || sv_maxclients->modified || sv_gametype->modified ) {
                char mapname[MAX_QPATH];
 
                Com_Printf( "variable change -- restarting.\n" );

```

I've been digging into the issue today and I still don't have the full picture. Here are some of my findings.

1. Reproducing the issue.

For me the crash happens only with the release build. A bit of tweaking narrowed down the issue to `-DNDEBUG`  compiler option. This define usually disables `assert()` debug functionality. 
However here that define is also used to trigger another one in the source, the `HUNK_DEBUG` in `code/qcommon/q_shared.h`.

The hunks seems to be used for stuff like loading data from files (like savegames). The debug functionality adds a structure containing size, filename, etc at the start of allocations.
Hard coding padding over-allocation seems all that is needed to hide the problem.
 
Anyway, adding `-DNDEBUG` to the CFLAGS of the `make debug` allowed me to get a backtrace.
 
2. The crash.

```
Thread 1 "iowolfsp.x86_64" received signal SIGSEGV, Segmentation fault.
0x0000000000470266 in SV_SetConfigstring (index=23, val=0x7fffffffc970 "s=,0,0,0,0,0,0,0,0,1,0") at code/server/sv_init.c:157
157                             if ( client->gentity && ( client->gentity->r.svFlags & SVF_CASTAI ) ) {
(gdb) bt
#0  0x0000000000470266 in SV_SetConfigstring (index=23, val=0x7fffffffc970 "s=,0,0,0,0,0,0,0,0,1,0") at code/server/sv_init.c:157
#1  0x000000000046cffb in SV_GameSystemCalls (args=0x7fffffffc800) at code/server/sv_game.c:393
#2  0x0000000000482437 in VM_DllSyscall (arg=20) at code/qcommon/vm.c:356
#3  0x00007fff9e0e89c3 in trap_SetConfigstring (num=23, string=0x7fffffffc970 "s=,0,0,0,0,0,0,0,0,1,0") at code/game/g_syscalls.c:144
#4  0x00007fff9e021fd6 in G_SendMissionStats () at code/game/g_main.c:1164
#5  0x00007fff9e09fea4 in G_SpawnItem (ent=0x7fff9e168650 <g_entities+242256>, item=0x7fff9e11b0f0 <bg_itemlist+272>) at code/game/g_items.c:1201
#6  0x00007fff9e0cd6e5 in G_CallSpawn (ent=0x7fff9e168650 <g_entities+242256>) at code/game/g_spawn.c:701
#7  0x00007fff9e0cdce8 in G_SpawnGEntityFromSpawnVars () at code/game/g_spawn.c:867
#8  0x00007fff9e0ce28d in G_SpawnEntitiesFromString () at code/game/g_spawn.c:1049
#9  0x00007fff9e0223e4 in G_InitGame (levelTime=3950, randomSeed=600624, restart=1) at code/game/g_main.c:1298
#10 0x00007fff9e02043f in vmMain (command=0, arg0=3950, arg1=600624, arg2=1, arg3=140737353854976, arg4=0, arg5=4294967296, arg6=4633936, arg7=140737488346040, arg8=140737488343312, arg9=4652229,
    arg10=140737488343456, arg11=4606988) at code/game/g_main.c:285
#11 0x00000000004832d1 in VM_Call (vm=0x31ed540 <vmTable>, callnum=0) at code/qcommon/vm.c:851
#12 0x000000000046fc11 in SV_InitGameVM (restart=qtrue) at code/server/sv_game.c:929
#13 0x000000000046fcc5 in SV_RestartGameProgs () at code/server/sv_game.c:959
#14 0x0000000000464c0c in SV_MapRestart_f () at code/server/sv_ccmds.c:422
#15 0x000000000043b141 in Cmd_ExecuteString (text=0x7fffffffd1e0 "map_restart") at code/qcommon/cmd.c:781
#16 0x000000000043a789 in Cbuf_Execute () at code/qcommon/cmd.c:251
#17 0x000000000043f591 in Com_Frame () at code/qcommon/common.c:2838
#18 0x00000000004e12d3 in main (argc=1, argv=0x7fffffffdba8) at code/sys/sys_main.c:764

(gdb) print client->gentity
$1 = (sharedEntity_t *) 0x7fffd2d2d400
(gdb) print client->gentity->r
Cannot access memory at address 0x7fffd2d2d520
(gdb) print *client->gentity
Cannot access memory at address 0x7fffd2d2d400
(gdb) print i
$2 = 0
(gdb) print svs.clients
$3 = (client_t *) 0x7fffd3444010
(gdb) print client
$4 = (client_t *) 0x7fffd3444010
(gdb) print client->state
$5 = CS_ACTIVE
(gdb) print index
$6 = 23

```

The code line of the function that crashes is:
```
// RF, don't send to bot/AI
if ( client->gentity && ( client->gentity->r.svFlags & SVF_CASTAI ) ) {
        continue;
}
```
Apparently `client->gentity` looks like it might be a valid pointer, but points to a non-existent memory region.

A little poking in the code showed that this pointer is usually filled by the `SV_GentityNum(i)` function, where `i` is an integer index. The entities there seems to be picked from another list, that is usually passed by the client... it's complicated.

To keep thing simple I decided to add check, if the index is in the range...

3. Out of bound indexes.

```
iowolfsp.x86_64: code/server/sv_game.c:50: SV_GentityNum: Assertion `num >= 0 && num < sv.num_entities' failed.

Thread 1 "iowolfsp.x86_64" received signal SIGABRT, Aborted.
0x00007ffff769d7a1 in pthread_kill@@GLIBC_2.34 () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff769d7a1 in pthread_kill@@GLIBC_2.34 () from /lib64/libc.so.6
#1  0x00007ffff7644092 in raise () from /lib64/libc.so.6
#2  0x00007ffff7628ed2 in abort () from /lib64/libc.so.6
#3  0x00007ffff7628e69 in __assert_fail_base.cold () from /lib64/libc.so.6
#4  0x000000000046b336 in SV_GentityNum (num=816) at code/server/sv_game.c:50
#5  0x000000000046b410 in SV_GEntityForSvEntity (svEnt=0x30d7140 <sv+336288>) at code/server/sv_game.c:76
#6  0x0000000000477319 in SV_AreaEntities_r (node=0x31d9740 <sv_worldSectors>, ap=0x7fffffffb540) at code/server/sv_world.c:409
#7  0x0000000000477557 in SV_AreaEntities (mins=0x7fffffffc650, maxs=0x7fffffffc65c, entityList=0x7fffffffb5c0, maxcount=1024) at code/server/sv_world.c:456
#8  0x0000000000477698 in SV_ClipMoveToEntities (clip=0x7fffffffc650) at code/server/sv_world.c:535
#9  0x0000000000477cbb in SV_Trace (results=0x7fffffffc9b0, start=0x7fffaf764878 <g_entities+226424>, mins=0x7fffffffc9a4, maxs=0x7fffffffc998, end=0x7fffffffc9f4, passEntityNum=137, contentmask=33751041,
    capsule=0) at code/server/sv_world.c:666
#10 0x000000000046d248 in SV_GameSystemCalls (args=0x7fffffffc7d0) at code/server/sv_game.c:379
#11 0x0000000000482870 in VM_DllSyscall (arg=26) at code/qcommon/vm.c:356
#12 0x00007fffaf6e8b34 in trap_Trace (results=0x7fffffffc9b0, start=0x7fffaf764878 <g_entities+226424>, mins=0x7fffffffc9a4, maxs=0x7fffffffc998, end=0x7fffffffc9f4, passEntityNum=137, contentmask=33751041)
    at code/game/g_syscalls.c:168
#13 0x00007fffaf65374e in SP_ai_marker (ent=0x7fffaf7645f0 <g_entities+225776>) at code/game/ai_cast_script_ents.c:86
#14 0x00007fffaf6cd766 in G_CallSpawn (ent=0x7fffaf7645f0 <g_entities+225776>) at code/game/g_spawn.c:710
#15 0x00007fffaf6cdd05 in G_SpawnGEntityFromSpawnVars () at code/game/g_spawn.c:867
#16 0x00007fffaf6ce2aa in G_SpawnEntitiesFromString () at code/game/g_spawn.c:1049
#17 0x00007fffaf6223e4 in G_InitGame (levelTime=863800, randomSeed=68717, restart=1) at code/game/g_main.c:1298
#18 0x00007fffaf62043f in vmMain (command=0, arg0=863800, arg1=68717, arg2=1, arg3=140737353854976, arg4=0, arg5=4294967296, arg6=4634985, arg7=140737488346024, arg8=140737488343296, arg9=4653278,
    arg10=140737488343440, arg11=4607991) at code/game/g_main.c:285
#19 0x000000000048373a in VM_Call (vm=0x31f0540 <vmTable>, callnum=0) at code/qcommon/vm.c:851
#20 0x000000000047002a in SV_InitGameVM (restart=qtrue) at code/server/sv_game.c:931
#21 0x00000000004700de in SV_RestartGameProgs () at code/server/sv_game.c:961
#22 0x0000000000464ff7 in SV_MapRestart_f () at code/server/sv_ccmds.c:422
#23 0x000000000043b315 in Cmd_ExecuteString (text=0x7fffffffd1d0 "map_restart") at code/qcommon/cmd.c:781
#24 0x000000000043a95d in Cbuf_Execute () at code/qcommon/cmd.c:251
#25 0x000000000043f908 in Com_Frame () at code/qcommon/common.c:2838
#26 0x00000000004e1eb5 in main (argc=1, argv=0x7fffffffdb98) at code/sys/sys_main.c:764
(gdb) up 4
#4  0x000000000046b336 in SV_GentityNum (num=816) at code/server/sv_game.c:50
50              assert( num >= 0 && num < sv.num_entities);
(gdb) print num
$1 = 816
(gdb) print sv.num_entities
$2 = 138
```
Apparently the entities list has been replaced with smaller one, while some entities are still been referenced.

I think this check triggers earlier than the other crash, while still been in the same code-path. Using it should make it easier to reproduce and solve the bug.

I don't know if I'll have the time and patience to dig deeper. I hope somebody who knows the code could save me the effort.

**Comment by MAN-AT-ARMS** [comment]
I'm unable to reproduce the crash which is weird.

Can you try replacing lines 343-351 to the original code:

	if ( Cmd_Argc() > 1 ) {
		delay = atoi( Cmd_Argv( 1 ) );
	} else {
		if ( sv_gametype->integer == GT_SINGLE_PLAYER ) { // (SA) no pause by default in sp
			delay = 0;
		} else {
			delay = 5;
		}
	}

See if that changes anything for you.
If not, I may implement your workaround.

**Comment by iiv3** [comment]
I feel stupid...
I was using the last release, assuming it should be most stable version.

Most likely, the bug has been fixed by 072bf3c in 2023. It's not in the release because atm the last release is from 2019.

I cannot reproduce any of the above issues with current git.
I didn't even try your patch...

Still in two days and many reloads the game did crash two times when reloading.
Here is the backtrace from the third crash:
```
Thread 1 "iowolfsp.x86_64" received signal SIGSEGV, Segmentation fault.
CG_EntityEvent (cent=0x7fff0fb79008 <cg_entities+190632>, position=0x7fff0fb79c74 <cg_entities+193812>) at code/cgame/cg_event.c:1566
1566                                    trap_S_StartSound( NULL, es->number, CHAN_BODY, cgs.media.footsteps[ ci->modelInfo->footsteps ][footstepcnt] );
(gdb) bt
#0  CG_EntityEvent (cent=0x7fff0fb79008 <cg_entities+190632>, position=0x7fff0fb79c74 <cg_entities+193812>) at code/cgame/cg_event.c:1566
#1  0x00007fff0fa4b286 in CG_CheckEvents (cent=0x7fff0fb79008 <cg_entities+190632>) at code/cgame/cg_event.c:2837
#2  0x00007fff0fa85497 in CG_TransitionEntity (cent=0x7fff0fb79008 <cg_entities+190632>) at code/cgame/cg_snapshot.c:122
#3  0x00007fff0fa85912 in CG_TransitionSnapshot () at code/cgame/cg_snapshot.c:243
#4  0x00007fff0fa86196 in CG_ProcessSnapshots () at code/cgame/cg_snapshot.c:508
#5  0x00007fff0fa8f311 in CG_DrawActiveFrame (serverTime=551018, stereoView=STEREO_CENTER, demoPlayback=qfalse) at code/cgame/cg_view.c:1496
#6  0x00007fff0fa0d3de in vmMain (command=3, arg0=551018, arg1=0, arg2=0, arg3=10349372, arg4=140737354125312, arg5=4294957896, arg6=140737488344000, arg7=4339178, arg8=10349372, arg9=5780605,
    arg10=429454507419457, arg11=15906304) at code/cgame/cg_main.c:61
#7  0x0000000000483eb2 in VM_Call (vm=0x32bfcb0 <vmTable+464>, callnum=3) at code/qcommon/vm.c:851
#8  0x0000000000409a85 in CL_CGameRendering (stereo=STEREO_CENTER) at code/client/cl_cgame.c:1043
#9  0x00000000004235ea in SCR_DrawScreenField (stereoFrame=STEREO_CENTER) at code/client/cl_scrn.c:533
#10 0x0000000000423708 in SCR_UpdateScreen () at code/client/cl_scrn.c:587
#11 0x000000000041c344 in CL_Frame (msec=200) at code/client/cl_main.c:3050
#12 0x000000000043f97c in Com_Frame () at code/qcommon/common.c:2847
#13 0x00000000004e2669 in main (argc=1, argv=0x7fffffffdb38) at code/sys/sys_main.c:764
(gdb) print es
$1 = (entityState_t *) 0x7fff0fb79008 <cg_entities+190632>
(gdb) print *es
$2 = {number = 47, eType = 1, eFlags = 393364, pos = {trType = TR_LINEAR_STOP, trTime = 550850, trDuration = 50, trBase = {-188.636322, -714.740051, 56.1490479}, trDelta = {-45, 69, 0}}, apos = {
    trType = TR_INTERPOLATE, trTime = 0, trDuration = 0, trBase = {0, 123.832397, 0}, trDelta = {0, 0, 0}}, time = 0, time2 = 0, origin = {-176, -250, 56}, origin2 = {0, 0, 0}, angles = {0, 0, 0}, angles2 = {
    0, 0, 0}, otherEntityNum = 0, otherEntityNum2 = 0, groundEntityNum = 1022, constantLight = 0, dl_intensity = 0, loopSound = 0, modelindex = 0, modelindex2 = 0, clientNum = 47, frame = 0, solid = 4724754,
  event = 1, eventParm = 0, eventSequence = 13, events = {1, 1, 1, 1}, eventParms = {0, 0, 0, 0}, powerups = 0, weapon = 17, legsAnim = 44, torsoAnim = 556, density = 0, dmgFlags = 0, onFireStart = 0,
  onFireEnd = 0, aiChar = 12, teamNum = 0, effect1Time = 0, effect2Time = 0, effect3Time = 0, aiState = AISTATE_ALERT, animMovetype = 7}
(gdb) print es->number
$3 = 47
(gdb) print cgs
value of type `cgs_t' requires 167432 bytes, which is more than max-value-size
(gdb) print cgs.gameState
$4 = {stringOffsets = {1, 560, 0, 0, 0, 0, 780, 782, 0, 0, 0, 0, 784, 791, 0, 0, 0, 0, 0, 0, 0, 0, 0, 793, 0, 0, 0, 817, 887, 901, 943, 0, 0, 996, 1033, 1069, 1105, 1127, 0 <repeats 251 times>, 1164, 1179,
    1213, 1252, 1295, 1319, 1351, 1377, 1403, 1430, 1454, 1484, 1516, 1545, 1556, 1567, 1579, 1590, 1602, 1614, 1627, 1639, 1651, 1664, 1676, 1689, 1705, 1732, 1743, 1754, 1766, 1777, 1789, 1801, 1814, 1826,
    1838, 1851, 1863, 1876, 1892, 1917, 1939, 1964, 1991, 2018, 2042, 2065, 2099, 2133, 2167, 2206, 2243, 2280, 2318, 2356, 2394, 2416, 2436, 2456, 2476, 2493, 2514, 2534, 2554, 2578, 2603, 2628, 2650, 2671,
    2692, 2714, 2737, 2754, 2770, 2792, 2813, 2828, 2843, 2860, 2881, 2903, 2925, 2951, 2978, 3002, 3026, 3048, 3071, 3088, 3104, 3126, 3147, 3162, 3177, 3194, 3215, 3231, 3247, 3263, 3279, 3300, 3322, 3338,
    3353, 3374, 3394, 3408, 3441, 3475, 3495, 3511, 3529, 3548, 3561, 3573, 3591, 3608, 3619, 3651, 3683, 3700, 3740, 3780, 3812, 3860, 0 <repeats 129 times>, 3866, 3926, 4009, 4092, 4175, 4258, 4341, 4424,
    4507, 4590, 4673, 4756, 4839, 4922, 5005, 5088...},
  stringData = "\000\\g_enableBreath\\1\\g_soldierChargeTime\\20000\\g_LTChargeTime\\20000\\g_engineerChargeTime\\30000\\g_medicChargeTime\\45000\\g_bluelimbotime\\30000\\g_redlimbotime\\30000\\gamename\\main\\sv_allowAnonymous\\0\\sv_pri"..., dataCount = 8651}
(gdb) print ci->modelInfo
$5 = (animModelInfo_t *) 0x7fff1509e9a0
(gdb) print ci->modelInfo->footsteps
Cannot access memory at address 0x7fff1509e9e4
(gdb) print footstepcnt
$6 = 0
```

It's completely different codepath than the ones before, but it still happens when reloading the same level.
